CREATE TABLE IF NOT EXISTS `students`(
	`studentId` VARCHAR(8) PRIMARY KEY COMMENT "学生学号",
	`name` VARCHAR(15) NOT NULL COMMENT "学生姓名"
)ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `teachers` (
	`teacherId` VARCHAR(10) PRIMARY KEY COMMENT "教师编号",
	`name` VARCHAR(15) NOT NULL COMMENT "教师姓名"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `accounts` (
	`account` VARCHAR(15) PRIMARY KEY COMMENT "登录账号",
	`password` VARCHAR(15) NOT NULL COMMENT "登录密码",
	`personId` VARCHAR(10) NOT NULL COMMENT "人员编号",
	`personType` BOOL NOT NULL COMMENT "人员类别"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `paper` (
	`paperId` INT PRIMARY KEY AUTO_INCREMENT COMMENT "试卷编号",
	`subjectId` VARCHAR(10) NOT NULL COMMENT "科目编号",
	`name` VARCHAR(15) NOT NULL COMMENT "试卷名称",
	`describe` VARCHAR(200) COMMENT "试卷描述",
	`teacherId` VARCHAR(10) NOT NULL COMMENT "出卷教师编号"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `subject` (
	`subjectId` VARCHAR(10) PRIMARY KEY COMMENT "科目编号",
	`name` VARCHAR(15) NOT NULL COMMENT "科目名称",
	`teacherId` VARCHAR(10) NOT NULL COMMENT "教师编号"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `paper_question` (
	`id` INT PRIMARY KEY AUTO_INCREMENT COMMENT "序号",
	`paperId` INT NOT NULL COMMENT "试卷编号",
	`questionId` INT NOT NULL COMMENT "题目编号",
	`fullScore` INT NOT NULL COMMENT "题目满分分数"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `question` (
	`questionId` INT PRIMARY KEY AUTO_INCREMENT COMMENT "题目编号",
	`title` VARCHAR(100) NOT NULL COMMENT "题目标题",
	`content` VARCHAR(1000) NOT NULL COMMENT "题目问题"
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `student_answer` (
	`id` INT PRIMARY KEY AUTO_INCREMENT COMMENT "序号",
	`paperId` INT NOT NULL COMMENT "试卷编号",
	`questionId` INT NOT NULL COMMENT "题目编号",
	`studentId` VARCHAR(8) NOT NULL COMMENT "学生编号",
	`answer` TEXT NOT NULL COMMENT "学生答案",
	`score` INT COMMENT "得分"
);

CREATE TABLE IF NOT EXISTS `score` (
	`id` INT PRIMARY KEY AUTO_INCREMENT COMMENT "序号",
	`studentId` VARCHAR(8) NOT NULL COMMENT "学生编号",
	`paperId` INT NOT NULL COMMENT "试卷编号",
	`score` INT COMMENT "总分"
);

CREATE TABLE IF NOT EXISTS `subject_signup`(
	`id` INT AUTO_INCREMENT PRIMARY KEY COMMENT "序号",
	`subjectId` VARCHAR(10) NOT NULL COMMENT "科目编号",
	`studentId` VARCHAR(8) NOT NULL COMMENT "学生学号"
);

